version: "2"         # required to adjust maintainability checks
checks:
  similar-code:
    config:
      threshold: 70
  identical-code:
    config:
      threshold: 70
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "Mercadona.Backend/Data/Migrations/"
  - "Mercadona.Backend/System.Text.RegularExpressions.Generator/"
  - "Mercadona.Tests/"
  - "docfx_project/"