version: '3.4'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "mercadona"
      POSTGRES_PASSWORD: "mercadonaStudi"
      POSTGRES_DB: "mercadonadb"
  mercadona.backend:
    image: ghcr.io/damienhoareau/mercadonastudi:main
    container_name: mercadona.backend
    depends_on:
      - postgres
    ports:
      - 80:80
      - 443:443
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: https://+:443;http://+:80
      ApplicationUrl: https://cosmosdeveloppement.ddns.com
      LettuceEncrypt:DomainNames: [cosmosdeveloppement.ddns.com]
      ConnectionStrings:DefaultConnection: "host=postgres;Port=5432;Database=mercadonadb;User Id=mercadona;Password=mercadonaStudi;"
volumes:
  db_volume:
  